language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: client
      before_install: cd client
      script: npm run lint
      script: npm run test
    - stage: server
      before_install: cd server
      script: npm run lint
